# Generated by Django 5.1.7 on 2025-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_rename_librarian_library_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
